# Generated by Django 3.0.3 on 2021-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightpillars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eightpillardata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eightpillardata',
            name='ticker',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
