# Generated by Django 3.0.3 on 2021-05-31 09:35

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eightpillars', '0002_auto_20210531_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eightpillardata',
            name='Eps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='Pe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='are_shares_outstanding_shrinking',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='average_cash_flow',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='cash_flow_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_cash_flow_growing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_dividend_yield_affordable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_market_price_worth',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_net_income_growing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_pe_acceptable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_profit_margin_acceptable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_quick_ratio_positive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='is_revenue_growing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='latest_net_income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='latest_revenue',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='latest_shares_outstanding',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='market_cap',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eightpillardata',
            name='shares_outstanding',
            field=models.IntegerField(null=True),
        ),
    ]
