from django.db import models
from djmoney.models.fields import MoneyField
class EightPillarData(models.Model):
    ticker = models.CharField(max_length=10, null=False)
    market_cap = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    Eps = models.IntegerField(null=True)
    Pe = models.IntegerField(null=True)
    is_pe_acceptable = models.BooleanField(null=True)
    profit_margin = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    is_profit_margin_acceptable = models.BooleanField(null=True)
    latest_revenue = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_revenue_growing = models.BooleanField(null=True)
    latest_net_income = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_net_income_growing = models.BooleanField(null=True)
    latest_shares_outstanding = models.IntegerField(null=True)
    shares_outstanding = models.IntegerField(null=True)
    are_shares_outstanding_shrinking = models.BooleanField(null=True)
    is_quick_ratio_positive = models.BooleanField(null=True)
    is_cash_flow_growing = models.BooleanField(null=True)
    average_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_dividend_yield_affordable = models.BooleanField(null=True)
    cash_flow_value = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_market_price_worth = models.BooleanField(null=True)
    last_updated = models.DateTimeField(auto_now=True, null=False)
